### PR TITLE
Adapted the system of units to Geant4, using PDG 2019 values.

### PR DESCRIPTION
**Pull request by agheata**
Adapted to changes done in 17.07.20 in CLHEP

### CODE REVIEW

**Comment by hahnjo** [comment]
Without the discussed changes in VecGeom, we'll now run into trouble for the magnetic field, right?

**Comment by agheata** [comment]
> Without the discussed changes in VecGeom, we'll now run into trouble for the magnetic field, right?

Correct, I'm doing the necessary change in VecGeom, let's wait until that one is merged first.

**Comment by agheata** [comment]
OK, the change in VecGeom is now merged in the master. This can be merged as well, but to avoid compilation errors before adopting the VecGeom master, I commented out in the examples the lines that need to be activated before GDML loading for the units to be taken in mm.
```  
  // The vecgeom unit has to be changed before loading the geometry
  // vecgeom::GeoManager::SetMillimeterUnit(1.); // activate this line after migrating to VecGeom master
```

**Comment by hahnjo** [comment]
> OK, the change in VecGeom is now merged in the master. This can be merged as well, but to avoid compilation errors before adopting the VecGeom master, I commented out in the examples the lines that need to be activated before GDML loading for the units to be taken in mm.

I don't think it's a good idea to get wrong results from the examples by default. So there is no other way than using the new function?

**Comment by agheata** [comment]
> > OK, the change in VecGeom is now merged in the master. This can be merged as well, but to avoid compilation errors before adopting the VecGeom master, I commented out in the examples the lines that need to be activated before GDML loading for the units to be taken in mm.
> 
> I don't think it's a good idea to get wrong results from the examples by default. So there is no other way than using the new function?

No, because VecGeom API does not provide units. When you ask for a length you get what was computed based on the numbers stored internally in VecGeom. The user has to decide if these represent cm/mm/something else. What I added is just a way to force VecGeom store a given value as internal representation for millimeter. But this does not make the examples fail by default, it just forces defining the VecGeom length unit, and then getting it back naturally w/o having to do runtime conversions.

**Comment by hahnjo** [comment]
Without the call, it will give different results when changing the units as done in this PR

**Comment by agheata** [comment]
> Without the call, it will give different results when changing the units as done in this PR

Yes, because VecGeom is units aware now (and has an internal unit cm which was before just implicit) and you would be misusing it if you assumed that the default unit was mm.

**Comment by agheata** [comment]
Can you think of a better alternative?

**Comment by hahnjo** [comment]
I think we should do either of:
1. Use the new API you added to VecGeom (after `cm` is fixed). Requires either `master` or asking for a new release.
2. Merge this PR and transform the units before calling VecGeom. Should be relatively straight-forward in the `LoopNavigator`.
3. Wait until we can do 1. and until then, transform the units before calling G4HepEm. That's what I currently have for the upcoming `example6`.

**Comment by agheata** [comment]
> I think we should do either of:
> 
> 1. Use the new API you added to VecGeom (after `cm` is fixed). Requires either `master` or asking for a new release.
> 2. Merge this PR and transform the units before calling VecGeom. Should be relatively straight-forward in the `LoopNavigator`.
> 3. Wait until we can do 1. and until then, transform the units before calling G4HepEm. That's what I currently have for the upcoming `example6`.

I think 1. can be done fast and requires fewer steps. I bound now setting the internal VecGeom unit to the vgdml::Frontend::Load method because it really depends on the method we use to create the geometry. Default is still mm=0.1, so we need to pass mm=1 as last parameter to the Load method for AdePT. We'll have a tag in VecGeom and change the minimum requirement in our cmake to match this (with this PR), then we can merge this safely. It might be that we're going to get errors in the CI if we don't update also there the VecGeom we build against. But we have to wait for the VecGeom tag first.

**Comment by agheata** [comment]
Indeed:
CMake Error at CMakeLists.txt:53 (find_package):
  Could not find a configuration file for package "VecGeom" that is
  compatible with requested version "1.1.10".

  The following configuration files were considered but not accepted:

    /cvmfs/sft-nightlies.cern.ch/lcg/views/devAdePT/Fri/x86_64-centos7-gcc8-opt/lib64/cmake/VecGeom/VecGeomConfig.cmake, version: 1.1.9

@peremato can you boost the version of vecgeom in the nightlies to 1.1.10?

**Comment by hahnjo** [comment]
Note that 1.1.10 incorrectly treats `cm` as `mm` (see https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/785/diffs#note_4176659), so we need to fix that and wait for 1.1.11

**Comment by agheata** [comment]
> Note that 1.1.10 incorrectly treats `cm` as `mm` (see https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/785/diffs#note_4176659), so we need to fix that and wait for 1.1.11

@hahnjo I saw your comment in VecGeom late, but the change was intentional. The convention is to interpret missing units in GDML as "mm" and the old behavior was inconsistent.

**Comment by hahnjo** [comment]
> > Note that 1.1.10 incorrectly treats `cm` as `mm` (see https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/785/diffs#note_4176659), so we need to fix that and wait for 1.1.11
> 
> @hahnjo I saw your comment in VecGeom late, but the change was intentional. The convention is to interpret missing units in GDML as "mm" and the old behavior was inconsistent.

Then we need to add `cm` to the list of handled units. Just treating it as `mm` is definitely wrong and will be disastrous with `trackML.gdml`.

**Comment by peremato** [comment]
bot build

**Comment by agheata** [comment]
OK, nice spot @hahnjo, we have already 1.1.11 fixing this, and @peremato is making a VecGeom build using this

**Comment by peremato** [comment]
bot build

**Comment by agheata** [comment]
OK, I think this is ready to merge now

**Comment by hahnjo** [comment]
Hm, I'm getting different results from `example2` after this PR. For one, that's because we have to scale up the random values in the processes by a factor of 10 as well as the position:
```diff
diff --git a/examples/Example2/example2.cu b/examples/Example2/example2.cu
index 7b07003..aefbd58 100644
--- a/examples/Example2/example2.cu
+++ b/examples/Example2/example2.cu
@@ -191,7 +191,7 @@ void example2(const vecgeom::cxx::VPlacedVolume *world)
   track2->energy      = 30.0f;
   track2->energy_loss = 0.0f;
   //  track2->index = 2; // this is not use for the moment, but it should be a unique track index
-  track2->pos = {0, 0.05, 0};
+  track2->pos = {0, 0.5, 0};
   track2->dir = {1, 0, 0};
   init_track<<<1, 1>>>(track2, gpu_world);
   COPCORE_CUDA_CHECK(cudaDeviceSynchronize());
diff --git a/physics/processes/inc/energy_loss.h b/physics/processes/inc/energy_loss.h
index 2915fce..223e6a5 100644
--- a/physics/processes/inc/energy_loss.h
+++ b/physics/processes/inc/energy_loss.h
@@ -17,7 +17,7 @@ __device__ float energy_loss::GetPhysicsInteractionLength(int particle_index, ad
 {
   track *mytrack = &((*block)[particle_index]);
   // here I will need to calculate the IL based on the particle energy, material, etc
-  float current_length = mytrack->uniform() * 0.2f;
+  float current_length = mytrack->uniform() * 2.0f;
   return current_length;
 }

diff --git a/physics/processes/inc/pair_production.h b/physics/processes/inc/pair_production.h
index 0e52f78..b5a3a38 100644
--- a/physics/processes/inc/pair_production.h
+++ b/physics/processes/inc/pair_production.h
@@ -17,7 +17,7 @@ __device__ float pair_production::GetPhysicsInteractionLength(int particle_index
 {
   track *mytrack = &((*block)[particle_index]);
   // here I will need to calculate the IL based on the particle energy, material, etc
-  float current_length = mytrack->uniform() * 0.25f;
+  float current_length = mytrack->uniform() * 2.5f;
   return current_length;
 }

```

But even then, I get a different number of secondaries and number of hits...

(`example4` doesn't reproduce either, but I think that's a different reason...)

**Comment by agheata** [comment]
Can you track down why it diverges maybe by limiting the number of tracks?

**Comment by hahnjo** [comment]
We can avoid the difference in `example2` with
```diff
diff --git a/examples/Example2/example2.cu b/examples/Example2/example2.cu
index 7b07003..050748d 100644
--- a/examples/Example2/example2.cu
+++ b/examples/Example2/example2.cu
@@ -39,7 +39,7 @@ struct Scoring {
   }
 };

-constexpr double kPush = 1.e-8;
+constexpr double kPush = 1.e-7;

 // kernel select processes based on interaction lenght and put particles in the appropriate queues
 __global__ void DefinePhysicalStepLength(adept::BlockData<track> *block, process_list *proclist,
```
(which is odd enough that this makes a difference in the number of hits - it really shouldn't!)

**Comment by agheata** [comment]
> (which is odd enough that this makes a difference in the number of hits - it really shouldn't!)

If this causes extra or fewer calls to the rng, it is not. Can you count the calls to rng in an easy way in the 2 cases?

**Comment by hahnjo** [comment]
> > (which is odd enough that this makes a difference in the number of hits - it really shouldn't!)
> 
> If this causes extra or fewer calls to the rng, it is not. Can you count the calls to rng in an easy way in the 2 cases?

This is the amount that is pushed into a new volume, if this results in different call graph then that is still bad. But I didn't check, I'm currently looking into `example4` (which still doesn't reproduce even with #85). Probably because of different energies in the magnetic field. I'm trying to hunt down all constants that didn't have a unit before, and I think we should really understand the difference or we risk breaking some physics computation in the magnetic field...

**Comment by agheata** [comment]
> > > (which is odd enough that this makes a difference in the number of hits - it really shouldn't!)
> > 
> > 
> > If this causes extra or fewer calls to the rng, it is not. Can you count the calls to rng in an easy way in the 2 cases?
> 
> This is the amount that is pushed into a new volume, if this results in different call graph then that is still bad. But I didn't check, I'm currently looking into `example4` (which still doesn't reproduce even with #85). Probably because of different energies in the magnetic field. I'm trying to hunt down all constants that didn't have a unit before, and I think we should really understand the difference or we risk breaking some physics computation in the magnetic field...

The amount of a push actually can influence the call graph, in one case the track may be passing through a corner in the other it can actually enter the new volume, triggering computation of physics. So this is not bad if changing the tolerance to be unit-aware fixes the divergence. I agree though that we have to understand divergencies if any, before merging,

**Comment by agheata** [comment]
Note that this PR slightly changes also the electron charge, so the trajectories in field are a bit different, which may be enough to get a divergence.

**Comment by agheata** [comment]
This is now rebased on the master. Example4 shows now no divergence on my machine before and after applying this. @jonapost can you review this?

**Review by WitekPokorski — APPROVED** [review]
looks ok to me

**Comment by hahnjo** [comment]
FWIW I've posted the proposed changes I already mentioned above in #96 to restore the output of the existing examples.

**Pull request merged**
