### PR TITLE
Use G4endl with G4cout

### PR DESCRIPTION
**Pull request by hahnjo**
This gives the proper `G4WT` prefixes.

### CODE REVIEW

**Review by agheata — APPROVED** [review]

**Comment by agheata** [comment]
Actually the build failed due to:
```
CMake Error at examples/Example3/CMakeLists.txt:39 (add_executable):
  CMake doesn't support IPO for current compiler
```
This is due to this line in example3 cmake:
`set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)`
It looks like cmake changed the policy to generate an error if the compiler does not support it, as per: https://cmake.org/cmake/help/latest/policy/CMP0069.html

@hahnjo do you mind looking into this?

**Comment by hahnjo** [comment]
> Actually the build failed due to:
> 
> ```
> CMake Error at examples/Example3/CMakeLists.txt:39 (add_executable):
>   CMake doesn't support IPO for current compiler
> ```
> 
> This is due to this line in example3 cmake: `set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)` It looks like cmake changed the policy to generate an error if the compiler does not support it, as per: https://cmake.org/cmake/help/latest/policy/CMP0069.html

Sure, but this is not related to this pull request, is it?

**Comment by agheata** [comment]
> Sure, but this is not related to this pull request, is it?

No, this PR triggered it.

**Comment by hahnjo** [comment]
> > Sure, but this is not related to this pull request, is it?
> 
> No, this PR triggered it.

Not really, it was already there yesterday: http://cdash.cern.ch/index.php?project=AdePT&date=2023-07-12 (it also wouldn't make sense for this change to trigger a CMake problem...)

**Comment by agheata** [comment]
I meant it revealed it, it was triggered probably by an upgrade of cmake on the test machines. Did not notice it was there in the nightlies. The question is, we fix it by removing the cmake line in the example, or applying IPO only where available? It is easy just to remove, but maybe we will need it in future for other examples? What is your take?

**Comment by hahnjo** [comment]
I don't know, I don't think we need it right now. But `example3` is by Guilherme, so I don't really know why it is there in the first place.

**Comment by agheata** [comment]
@amadio do we need this CMAKE_INTERPROCEDURAL_OPTIMIZATION option in example3?

**Pull request merged**
