### PR TITLE
Create CopCore subproject

### PR DESCRIPTION
**Pull request by drbenmorgan**
As discussed in #14 and online, we should have a subproject in which we can put common types, utilities for working with coprocessors (GPU or otherwise). This implements the basic structure for this "CopCore" (favoured name in the issue) project:

- Location kept alongside AdePT for consistency
- It's a full CMake subproject to help with any future export to a dedicated repository
- It's implemented in CMake such that use is the same whether used via `add_subdirectory` or `find_package`, and there can be a noddy compile-time test of this.

At present, it *isn't* integrated in AdePT because I'd like to keep the commits separate to ease future separation, and we're now squash-merging PRs. My first thought is therefore to merge this, then a separate PR to add the integration, but let me know how you'd prefer to proceed.

### CODE REVIEW

**Review by agheata — APPROVED** [review]
Looks good to me

**Comment by drbenmorgan** [comment]
Thanks @agheata, I'll merge then submit the additional PR to integrate the subproject with the AdePT build.

**Comment by graeme-a-stewart** [comment]
Hi @drbenmorgan - all substantive points look fine. Can we remove the unneeded licenses? I think CC-BY-ND-4.0 and GPL-3 are not needed right now... oh, too late, never mind!

**Comment by drbenmorgan** [comment]
Hi @graeme-a-stewart, oops, sorry! I'll look at removing those in a future PR!

**Pull request merged**
