### PR TITLE
Delete toy examples

### PR DESCRIPTION
**Pull request by hahnjo**
These are very old and not useful anymore, plus the Alpaka build seems again broken in Jenkins.

### CODE REVIEW

**Review by agheata — COMMENTED** [review]
For the Alpaka one, maybe keep its folder for a while more (for the sake of the Alpaka integration demonstration), but remove the folder from the compilation?

**Comment by hahnjo** [comment]
We can always go back to the `git` history for that, no?

**Comment by bernhardmgruber** [comment]
So the alpaka example failed to compiled on my machine for a while, since I had alpaka 0.9.0 installed. So I fixed it in: #206. Quite recently I noticed then that the alpaka version on LCG was old (0.4.0 IIRC), so I requested that to be updated to 0.9.0 as well. I know the update was released on the LCG nightlies, but I don't know yet whether it is part of an LCG release yet. Maybe that causes the problem.

**Comment by hahnjo** [comment]
I can reproduce the build failure with the tag 0.9.0 *unless* I add `-Dalpaka_ACC_GPU_CUDA_ENABLE=ON` to the AdePT build. I don't know if that's needed now...

**Comment by agheata** [comment]
OK, it seems that struggling to keep this compiling does not worth it. However, the code is not big so if we just keep it un-compiled would make it easier to revive it at some point when we'll eventually be able to use Alpaka in more examples, without having to dig it out from history. So I vote for that.

**Comment by bernhardmgruber** [comment]
> I can reproduce the build failure with the tag 0.9.0 unless I add -Dalpaka_ACC_GPU_CUDA_ENABLE=ON to the AdePT build. I don't know if that's needed now...

Oh yes, that needs to be enabled. Alpaka changed enabling backends by default at some time and now backends must be explicitly enabled by the user. Since the alpaka fisherprice example makes explicit use of types from the CUDA backend, e.g. `alpaka::rand::engine::uniform_cuda_hip::Xor`, the backend must be turned on to successfully compile the example.

I am sorry I did not notice this extra step earlier, I am already so used to this behavior of alpaka.

I would suggest to enable the backend explicitly in the `CMakeLists.txt` of the alpaka fisherprice example.

**Comment by bernhardmgruber** [comment]
Let's give it a try: #221

**Pull request closed without merging**
