### PR TITLE
Adding CTest/Jenkins infrastructure

### PR DESCRIPTION
**Pull request by peremato**
Added Jenkinsfile with the basic pipeline.
Added the script jenkins/adept-ctest.cmake to drive the update, configuration, build and test and publish results to [Cdash](https://cdash.cern.ch/index.php?project=AdePT)
The initial jenkins jobs (nightly for the time being) are available at https://lcgapp-services.cern.ch/spi-jenkins/view/AdePT/

### CODE REVIEW

**Comment by peremato** [comment]
@bot build

**Comment by hahnjo** [comment]
@peremato

**Comment by hahnjo** [comment]
(sorry for the noise, clicked wrongly)

@peremato I'm not familiar with Jenkins, so can't really comment on the configuration. From a user's perspective, can we have the result of the Jenkins pipeline visible directly from the PR (as we do for ROOT)?

**Comment by peremato** [comment]
> (sorry for the noise, clicked wrongly)
> 
> @peremato I'm not familiar with Jenkins, so can't really comment on the configuration. From a user's perspective, can we have the result of the Jenkins pipeline visible directly from the PR (as we do for ROOT)?

I am currently trying to setup this.

**Comment by peremato** [comment]
Bot build!

**Comment by peremato** [comment]
Bot build!

**Comment by peremato** [comment]
Bot build!

**Review by WitekPokorski — APPROVED** [review]
looks good!

**Pull request merged**
