### PR TITLE
Add missing particle class.

### PR DESCRIPTION
**Pull request by shefmarkh**
The particle.h file form the FisherPrice_Alpaka directory was missing.
This MR add that.

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
Hi @shefmarkh - sorry, I think this got overlooked at it had no reviewer. I'm happy to check it, but it might be next week as I need to first install alpaka onto the machine I use.

**Comment by shefmarkh** [comment]
no problem, next week is fine.

Cheers,

Mark

**Comment by agheata** [comment]
Any progress here?

**Comment by shefmarkh** [comment]
I don't think there is anything to do from my side, just needs a review.

Cheers,

Mark

**Comment by graeme-a-stewart** [comment]
My bad - I completely forgot to follow-up on this (I get too many github alerts for that to be useful). Unfortunately `titanx` is down right now, but I have asked for GPU access via IT. So this week fror sure...

**Comment by graeme-a-stewart** [comment]
Hi @shefmarkh 

So, finally taking a look at this... and it's not working at all well for me. Merging this with the current heard of master I get a lot of compilation errors. First I got a bunch of internal ones from Alpaka headers, but those were fixed by adding `-DALPAKA_ACC_GPU_CUDA_ENABLE=ON`. However, I still see:

```
/home/graemes/code/AdePT/examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu(118): error #20: identifier "dim" is undefined

/home/graemes/code/AdePT/examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu(118): error #65: expected a ";"

/home/graemes/code/AdePT/examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu(122): error #20: identifier "acc" is undefined

/home/graemes/code/AdePT/examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu(122): error #65: expected a ";"

/home/graemes/code/AdePT/examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu(125): error #276: name followed by "::" must be a class or namespace name

/home/graemes/code/AdePT/examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu(127): error #276: name followed by "::" must be a class or namespace name

/home/graemes/code/AdePT/examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu(131): error #276: name followed by "::" must be a class or namespace name

/home/graemes/code/AdePT/examples/FisherPrice_Alpaka/unitTests_alpaka_fisher_price.cu(131): error #254: type name is not allowed
```

Is there something else I'm missing as a cmake flag or is there a genuine problem that you can also see?

My setup is:

```
cmake -S ~/code/AdePT -B . -DVecGeom_DIR=$HOME/.local -DCMAKE_CUDA_ARCHITECTURES=61 -DCMAKE_CUDA_COMPILER=/opt/nvidia/cuda-11.0/bin/nvcc -DDCMAKE_PREFIX_PATH=~/.local -DALPAKA_ACC_GPU_CUDA_ENABLE=ON  -G Ninja
```

Thanks, Graeme

**Comment by shefmarkh** [comment]
I just checked out the branch and compiled that with:

cmake -S. -B./adept-build -DVecCore_DIR=/usr/local/lib64/cmake/veccore/ -DVecGeom_DIR=/usr/local/lib64/cmake/VecGeom/ -DCMAKE_PREFIX_PATH=/install/
cmake --build .

with no errors.

Similarly this also worked with the current master of the main adept GitHub (after adding the particleClass.h locally).

I wonder if the issue is the Ninja build is doing something differently? I was not able to test that - although I cloned ninja and built it in my home directory, using '-G Ninja" seems to generate cmake errors (perhaps the ninja location has to also be specified somehow).

 cmake -S. -B./adept-build -DVecCore_DIR=/usr/local/lib64/cmake/veccore/ -DVecGeom_DIR=/usr/local/lib64/cmake/VecGeom/ -DCMAKE_PREFIX_PATH=/install/ -G Ninja
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!


Cheers,

Mark

**Comment by shefmarkh** [comment]
hmm, after figuring out how to install ninja I was able to use that. That also seems to build ok for me with the command "ninja".

Cheers,

Mark

**Comment by graeme-a-stewart** [comment]
@shefmarkh - let me check my setup here and try and figure out what's up (but weird, eh, as alpaka is a header library, so one wouldn't expect any sort of runtime issues with it).

I can accept this PR anyway as clearly 

- the header is missing
- the problems are independent of having (or not) this header code

**Comment by graeme-a-stewart** [comment]
So... it seems the problem is with a bad interaction between alpaka and my machine, because I can reporoduce the error building the alpaka examples.

One quick question, @shefmarkh - which version of CUDA are you using? The machine I am on now has only CUDA 11.1 (with gcc 8.4), but I can remember that alpaka worked find earlier in the year with CUDA 10.X... From https://github.com/alpaka-group/alpaka#supported-compilers it looks like that should be supported.

**Comment by shefmarkh** [comment]
I am using 11.0.228 (with gcc 8.3.1)

Cheers,

Mark

**Review by graeme-a-stewart — APPROVED** [review]

**Comment by graeme-a-stewart** [comment]
OK, super weird and something I need to investigate further. However, I propose we accept this PR anyway as it's an orthogonal problem that my alpaka setup it broken.

**Pull request merged**
