### PR TITLE
Test GitHub <--> Jenkins

### PR DESCRIPTION
**Pull request by peremato**

### CODE REVIEW

**Comment by peremato** [comment]
bot build!

**Comment by peremato** [comment]
bot build!

**Comment by peremato** [comment]
@bot build!

**Comment by peremato** [comment]
@bot build!

**Comment by peremato** [comment]
@bot build!

**Comment by peremato** [comment]
run tests

**Comment by peremato** [comment]
run tests

**Comment by peremato** [comment]
run tests

**Comment by peremato** [comment]
@adept-bot build!

**Comment by peremato** [comment]
@adept-bot build!

**Comment by peremato** [comment]
@adept-bot build!

**Comment by peremato** [comment]
@adept-bot build!

**Comment by peremato** [comment]
@adept-bot build!

**Comment by smuzaffar** [comment]
run tests

**Comment by smuzaffar** [comment]
test this please

**Comment by smuzaffar** [comment]
@adept-bot build

**Comment by smuzaffar** [comment]
@adept-bot build

**Comment by smuzaffar** [comment]
run tests

**Comment by smuzaffar** [comment]
run tests

**Comment by smuzaffar** [comment]
run tests

**Comment by smuzaffar** [comment]
test this please

**Comment by smuzaffar** [comment]
run tests

**Comment by smuzaffar** [comment]
@phsft-bot build

**Comment by agheata** [comment]
@peremato Is this ready for merging?

**Comment by agheata** [comment]
Oh, I see it is just to test. Sorry for the noise.

**Comment by peremato** [comment]
@phsft-bot build

**Comment by peremato** [comment]
@adept-bot build

**Comment by peremato** [comment]
@adept-bot build

**Comment by peremato** [comment]
@agheata Can you please review and merge (with squash)

**Review by agheata — APPROVED** [review]

**Pull request merged**
