### PR TITLE
Rdc no circdeps

### PR DESCRIPTION
**Pull request by agheata**
This starts from commit 24098bbf3df14269ca51ed284751422920be4a03 of @drbenmorgan on https://github.com/apt-sim/AdePT/pull/279 

It restructures the code so that libAdePT_G4_integration depends on libAdePT library, but not the opposite. The libraries compile and the tests build OK, however the examples fail to link on my machine, giving:

```
/usr/bin/ld: ../../BuildProducts/lib/libAdePT.so: undefined reference to `__cudaRegisterLinkedBinary_2ab39261_14_HostScoring_cu_81555e38_561416'
/usr/bin/ld: ../../BuildProducts/lib/libAdePT_G4_integration.so: undefined reference to `__cudaRegisterLinkedBinary_0fc71ad9_23_AdePTTrackingManager_cu_9e5b2120_562716'
collect2: error: ld returned 1 exit status
```

### CODE REVIEW

**Comment by agheata** [comment]
The verbose link line is:
```
 cd /home/agheata/geant_src/AdePT/adept-build/examples/Example1 && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/example1.dir/link.txt --verbose=1
/usr/bin/c++ -O2 -g -DNDEBUG CMakeFiles/example1.dir/example1.cpp.o CMakeFiles/example1.dir/__/common/src/ParticleGun.cc.o CMakeFiles/example1.dir/__/common/src/ParticleGunMessenger.cc.o CMakeFiles/example1.dir/__/common/src/FTFP_BERT_HepEm.cc.o CMakeFiles/example1.dir/__/common/src/FTFP_BERT_AdePT.cc.o CMakeFiles/example1.dir/src/ActionInitialisation.cc.o CMakeFiles/example1.dir/src/DetectorConstruction.cc.o CMakeFiles/example1.dir/src/DetectorMessenger.cc.o CMakeFiles/example1.dir/src/EventAction.cc.o CMakeFiles/example1.dir/src/EventActionMessenger.cc.o CMakeFiles/example1.dir/src/SteppingAction.cc.o CMakeFiles/example1.dir/src/SimpleHit.cc.o CMakeFiles/example1.dir/src/PrimaryGeneratorAction.cc.o CMakeFiles/example1.dir/src/RunAction.cc.o CMakeFiles/example1.dir/src/SensitiveDetector.cc.o CMakeFiles/example1.dir/src/TrackingAction.cc.o CMakeFiles/example1.dir/__/common/src/HepMC3G4AsciiReader.cc.o CMakeFiles/example1.dir/__/common/src/HepMC3G4AsciiReaderMessenger.cc.o CMakeFiles/example1.dir/__/common/src/HepMC3G4Interface.cc.o -o ../../BuildProducts/bin/example1  -Wl,-rpath,/home/agheata/geant_src/hepmc3_install/lib:/home/agheata/geant_src/AdePT/adept-build/BuildProducts/lib:/home/agheata/geant_src/VecGeom_install/lib:/home/agheata/geant_src/g4hepem_install/lib:/home/agheata/geant4/geant4-v11.2.0.install/lib:/usr/local/lib /home/agheata/geant_src/hepmc3_install/lib/libHepMC3.so /home/agheata/geant_src/hepmc3_install/lib/libHepMC3search.so /home/agheata/geant_src/hepmc3_install/lib/libHepMC3rootIO.so ../../BuildProducts/lib/libAdePT_G4_integration_final.so ../../BuildProducts/lib/libAdePT_G4_integration.so ../../BuildProducts/lib/libAdePT.so /home/agheata/geant_src/VecGeom_install/lib/libvecgeomcuda.so /home/agheata/geant_src/VecGeom_install/lib/libvgdml.a /home/agheata/geant_src/VecGeom_install/lib/libvecgeom.a -lrt -lpthread -ldl /home/agheata/geant_src/g4hepem_install/lib/libg4HepEm.so /home/agheata/geant_src/g4hepem_install/lib/libg4HepEmInit.so /home/agheata/geant_src/g4hepem_install/lib/libg4HepEmRun.so /home/agheata/geant_src/g4hepem_install/lib/libg4HepEmData.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4Tree.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4FR.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4GMocren.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4visHepRep.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4RayTracer.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4VRML.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4ToolsSG.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4vis_management.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4modeling.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4interfaces.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.3 /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.15.3 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.3 /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4mctruth.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4geomtext.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4gdml.so /usr/local/lib/libxerces-c.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4error_propagation.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4readout.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4physicslists.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4run.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4event.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4tracking.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4parmodels.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4processes.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4analysis.so /usr/lib/x86_64-linux-gnu/libexpat.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4digits_hits.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4track.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4particles.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4geometry.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4materials.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4graphics_reps.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4intercoms.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4global.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4clhep.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4zlib.so /home/agheata/geant4/geant4-v11.2.0.install/lib/libG4ptl.so.2.3.3 
/usr/bin/ld: ../../BuildProducts/lib/libAdePT.so: undefined reference to `__cudaRegisterLinkedBinary_2ab39261_14_HostScoring_cu_81555e38_561416'
/usr/bin/ld: ../../BuildProducts/lib/libAdePT_G4_integration.so: undefined reference to `__cudaRegisterLinkedBinary_0fc71ad9_23_AdePTTrackingManager_cu_9e5b2120_562716'
collect2: error: ld returned 1 exit status
```

**Comment by agheata** [comment]
@drbenmorgan the missing symbols above seem to relate with missing the `-rdc=true`, but for example `AdePTTrackingManager.cu` is compiled with this option on:
```
[  7%] Building CUDA object CMakeFiles/AdePT_G4_integration_objects.dir/src/AdePTTrackingManager.cu.o
/usr/local/cuda-12.0/bin/nvcc -forward-unknown-to-host-compiler -DG4HepEm_CUDA_BUILD -DG4LIB_BUILD_DLL -DG4UI_USE_QT -DG4VERSION_NUM=1120 -DG4VIS_USE_TOOLSSG_QT_GLES -DG4VIS_USE_TOOLSSG_QT_ZB -DG4VIS_USE_TOOLSSG_X11_GLES -DHEPMC3_FOUND -DPTL_BUILD_DLL -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DVECCORE_ENABLE_CUDA --options-file CMakeFiles/AdePT_G4_integration_objects.dir/includes_CUDA.rsp -O2 -g -DNDEBUG -std=c++17 "--generate-code=arch=compute_75,code=[compute_75,sm_75]" -Xcompiler=-fPIC --generate-line-info --source-in-ptx -Xcudafe --diag_suppress=unrecognized_gcc_pragma -Xnvlink --suppress-stack-size-warning -Xcompiler=-faligned-new,-mavx2 -fPIC -MD -MT CMakeFiles/AdePT_G4_integration_objects.dir/src/AdePTTrackingManager.cu.o -MF CMakeFiles/AdePT_G4_integration_objects.dir/src/AdePTTrackingManager.cu.o.d -x cu -rdc=true -c /home/agheata/geant_src/AdePT/src/AdePTTrackingManager.cu -o CMakeFiles/AdePT_G4_integration_objects.dir/src/AdePTTrackingManager.cu.o
```

However, all the intermediate libraries that get created and the way they are linked look VERY intricate and hard to understand and the whole thing is very fragile. I don't know how to debug this...

**Comment by drbenmorgan** [comment]
> However, all the intermediate libraries that get created and the way they are linked look VERY intricate and hard to understand and the whole thing is very fragile. I don't know how to debug this...

They are, and it is. However, it's not doing anything different from what's done in VecGeom (which makes all of this necessary) or the initial link implementation. FWIW, I can build the changes here without issue on my local system (Alma 9) with either GCC 11.4 or 12.2 and with CUDA 12.0 or 12.3, plus a standard VecGeom CUDA enabled install.

To help debug, what I'd suggest is:

- Migrate the removal of the circular dependency to a fresh PR based on the current `master`. That will separate out any issues related to that - i.e. the _existing_ link structure on `master` should work.
- When that's merged, I'll rebase #279 onto that and we can go forward with that separately.

**Comment by agheata** [comment]
> * Migrate the removal of the circular dependency to a fresh PR based on the current `master`. That will separate out any issues related to that - i.e. the _existing_ link structure on `master` should work.

OK, let me do this first

**Pull request closed without merging**
